---
title: "AULA 12"
format: html
editor: visual
---

## 
```{r}
library(tidyverse)
library(readxl)

fungicidas <- read_excel ("dados-diversos.xlsx", "fungicida_campo")
```

##ANova Block Model

```{r}
aov_fung <- aov(sev ~trat + rep, data = fungicidas)
summary(aov_fung)
```

```{r}
library(performance)
library(DHARMa)
check_normality(aov_fung)
check_heteroscedasticity(aov_fung)
plot(simulateResiduals(aov_fung))
```
```{r}
library(emmeans)
means_fung <- emmeans(aov_fung, ~trat)
summary(means_fung)
```

```{r}
library(multcomp)
library(multcompView)
cld(means_fung)

plot(means_fung) + 
  coord_flip() +
  theme_bw()
```
##Subdivided Plot (Split-plot)

```{r}
milho <- read_excel("dados-diversos.xlsx", "milho")


aov_milho_bloco <- aov(index ~factor(block) + hybrid*method + Error(factor(block)/hybrid/method), data = milho)

summary(aov_milho_bloco)

```

```{r}
library(lme4)

milho$block <- as.factor(milho$block)
mix2 <- lmer(index ~block + hybrid*method + (1|block/hybrid), data = milho)

anova(mix2)
library(performance)
check_normality(mix2)
check_heteroscedasticity(mix2)
```


```{r}
milho$block <- as.factor(milho$block)
mix3 <- lmer(sqrt(index) ~ block + hybrid*method + (1|block/hybrid), data = milho)

```

```{r}
library(car)
Anova(mix3)
check_normality(mix3)
check_heteroscedasticity(mix3)
```

```{r}
means_mix2 <- emmeans(mix2, ~hybrid| method)
summary(means_mix2)
```

```{r}
cld(means_mix2)
```

```{r}
means_mix3 <- emmeans(mix3, ~method| hybrid)
cld(means_mix3)
```


