---
title: "AULA 4"
format: html
editor: visual
---

## 
```{r}
library(tidyverse)
library(ggplot2)
library(readxl)

library(csvread)
mg <- read_csv("dados-diversos2.csv")

mg |> 
  ggplot(aes(Irrigation, severity, shape = Irrigation))+
  geom_point(alpha = 0.5)

mg |> 
  #filter(rep ==1) |> 
ggplot(aes(day, severity, shape = Irrigation))+
  geom_point(alpha = 0.5)+
geom_line()+
facet_wrap(~rep)
```


```{r}
mg |> 
  filter(rep == 2) |> 
ggplot(aes(day, severity, shape = Irrigation))+
  geom_point(alpha = 0.5)+
geom_line()
```


```{r}
mg |> 
ggplot(aes(Irrigation, severity, shape = Irrigation))+
  geom_boxplot()+
geom_point(alpha = 0.5)
```


```{r}
mg |> 
  select(day, rep, severity) |> 
  group_by(day) |> 
  summarize(sev = mean(severity)) |> 
ggplot(aes(day, sev))+
  geom_point()
```


```{r}
mg2 <- mg |> 
  select(day, rep, severity) |> 
  group_by(day) |> 
  summarize(sev = mean(severity))  
  
 mg2 |>  
ggplot(aes(day, sev*100))+
  geom_point(size = 3, color = "darkorange")+
   geom_line(color = "darkorange")+
   ylim(0,100)+
   scale_x_continuous(breaks = c(0, 7, 14, 21, 28, 35, 42, 49, 56, 63))+
   scale_y_continuous(n.breaks = 10, limits = c(0,100))+
   labs(x = "Time (days)", y = "severity (%)", title = "my first ggplot", subtitle = "it is beautiful", caption = "Source: FIP 606")+
 theme_classic()+
   theme(plot.title = element_text(hjust = 0.5))
 
 
 
 ggsave("myfirstggplot.png", bg = "white", width = 4, height = 3)
```
