---
title: "AULA 5"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
library(readxl)

mg <- read_excel("dados-diversos.xlsx")
```

```{r}
mg |> 
ggplot(aes(trat,comp))+
  geom_boxplot(color = "red", fill = "blue", outlier.color = NA, width = 0.2)+
  geom_jitter(width = 0.1, height = 0, size = 2, color = "steelblue")+
  scale_y_continuous(limits = c(5, 20), n.breaks = 10)+
  labs(y = "lesion size (mm)",
       x = "")+
  theme_bw()


ggsave("second_graph.png", bg = "white")
```

```{r}
p_box <- mg |> 
  group_by(trat) |> 
  summarise(comp_mean = mean(comp),
            comp_sd = sd(comp)) |> 
            ggplot(aes(trat, comp_mean))+
            geom_col(color = "orange", fill = "orange", width = 0.5)+
          scale_y_continuous(limits = c(0, 20), n.breaks = 6)+
geom_errorbar(aes(ymin = comp_mean - comp_sd, 
                  ymax = comp_mean + comp_sd, 
                  width = 0.05))
```

```{r}
library(ggthemes)
p_means <- mg |> 
  group_by(trat) |> 
  summarise(comp_mean = mean(comp),
            comp_sd = sd(comp)) |> 
            ggplot(aes(trat, comp_mean))+
            geom_col(color = "orange", fill = "orange", width = 0.5)+
  geom_point()+
          scale_y_continuous(limits = c(6, 20), n.breaks = 6)+
geom_errorbar(aes(ymin = comp_mean - comp_sd, 
                  ymax = comp_mean + comp_sd, 
                  width = 0.1))+
  theme_classic()


ggsave("third_graph.png", bg = "white",
       width = 4, 
      height = 4)



```

```{r}
library(patchwork)
(p_box | p_means)+
plot_annotation(tag_levels = "A",
                title = "Impression graph")
ggsave("Fourth_graph.png")
```

```{r}
survey <- read_excel("dados-diversos.xlsx", 
                     sheet = "survey")

survey |> 
filter(state =="RS") |> 
count(species, residue) |> 
  ggplot(aes(species, n))+
  geom_col(width = 0.4, 
           fill = "steelblue")+
coord_flip()+
  facet_wrap(~residue, ncol = 1)+
  labs(x = "", y = "Number of isolates",
       title = "Horizontal bar plot",
       subtitle = "using ggplot")+
theme_bw()
ggsave("fifth_graph.png")

```
