---
title: "AULA 9"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
library(readxl)
data_mg <- read_excel("dados-diversos.xlsx")

dat2 <- data_mg |> 
  group_by(trat) |> 
  summarise (mean_comp = mean(comp),
             sd_comp = sd(comp),
             var_comp = var(comp),
             n = n(),
             se_comp = sd_comp / sqrt(n-1),
             ci = se_comp * qt(0.025, df = 9))
dat2
```

```{r}
dat2 |> 
  ggplot(aes(trat, mean_comp)) +
  geom_col(color = "orange", fill = "orange", width = 0.5) +
  geom_errorbar(aes(
    ymin = mean_comp - se_comp,
    ymax = mean_comp + se_comp), 
    width = 0.1) +
ylim(0, 20)
```

```{r}
dat2 |> 
  ggplot(aes(trat, mean_comp)) +
  geom_col(color = "orange", fill = "orange", width = 0.5) +
  geom_errorbar(aes(
    ymin = mean_comp - ci,
    ymax = mean_comp + ci), 
    width = 0.1) +
ylim(0, 20) +
  labs(x = "", y = "Mean size (mm)")
```

```{r}
data_mg2 <- data_mg |> 
  pivot_wider(1, 
              names_from = trat, 
              values_from = comp)
data_mg2
```

```{r}
t.test(data_mg2$Mg2, data_mg2$control, paired = F)
```

```{r}
data_mg |> 
  ggplot(aes(trat, comp)) +
geom_jitter(width = 0.5, shape = 2)
```

##homocedasticidade

```{r}
attach(data_mg2)
var.test(Mg2, control)
Mg2
control
```

##Normalidade

```{r}
shapiro.test(Mg2)
shapiro.test(control)
```

##Analyze visual normalidade

```{r}
qqnorm(Mg2)
qqline(Mg2)
qqnorm(control)
qqline(control)
```

##Preanalysis preparation

```{r}
library(readxl)
escala <- read_excel("dados-diversos.xlsx", "escala")
head(escala)

escala2 <- escala |>
  select(assessment, rater, acuracia) |> 
  pivot_wider(1, 
              names_from = assessment,
              values_from = acuracia)
escala2
```

```{r}
attach(escala2)
t.test(Aided1, Unaided,
       paired = TRUE,
       var.equal = FALSE)

var.test(Aided1, Unaided)
shapiro.test(Aided1)
```

```{r}
attach(escala2)
t_escala <- t.test(Aided1, Unaided,
       paired = TRUE,
       var.equal = FALSE)

var.test(Aided1, Unaided)
shapiro.test(Unaided)
library(report)
report(t_escala)
wilcox.test(Aided1, Unaided)

library(rstatix)
```

```{r}
escala |> 
 ggplot(aes(assessment, acuracia)) +
  geom_boxplot()
```

```{r}
escala |> 
 ggplot(aes(assessment, precisao)) +
  geom_boxplot()
```
