---
title: "AULA 17"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
library(readxl)
library(gsheet)
dat <- gsheet2tbl("https://docs.google.com/spreadsheets/u/3/d/15pCj0zljvd-TGECe67OMt6sa21xO8BqUgv4d-kU8qi8/edit?usp=drive_web&ouid=112660568480999087067")
```

```{r}
options(scipen=999)
dat2 <- dat |> 
  select(-Isolate, -Population) |> 
  group_by(Code, Year, Dose) |> 
  summarise(GC_mean = mean(GC))

FGT152 <- dat2 |> 
  filter(Code == "FGT152")

FGT152 |> 
  ggplot(aes(factor(Dose), GC_mean)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Code)

dat2 |> 
  ggplot(aes(factor(Dose), GC_mean)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Code)
```

##EC50 with DRM package

```{r}
library(drc)
drcl <- drm(GC_mean ~ Dose, data = FGT152, fct = LL.3())
summary(drcl)
plot(drcl)
ED(drcl, 50, interval = "delta")
```

```{r}
library(drc)
drc2 <- drm(GC_mean ~ Dose, data = FGT152, fct = W1.3())
summary(drc2)
plot(drc2)
ED(drc2, 50, interval = "delta")
```

```{r}
AIC(drcl)
AIC(drc2)
```

##Kaique developed a package called ec50estimator

```{r}
library(ec50estimator)
df_ec50 <- estimate_EC50(GC_mean ~Dose,
                         data = dat2,
                         isolate_col = "Code",
                         interval = "delta",
                         fct = drc::LL.3())
df_ec50 |> 
  ggplot(aes(Estimate)) +
  geom_histogram()
```

```{r}
df_ec50 |> 
  ggplot(aes(Estimate, reorder(ID, Estimate))) +
  geom_point() +
  geom_errorbar(aes(xmin=Lower,
                    xmax=Upper,
                    width =0.1)) +
  xlim(0,30)
```
