---
title: "AULA 10"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
library(readxl)
library(viridis)
library(viridisLite)
micelial <- read_excel("dados-diversos.xlsx", "micelial")
head(micelial)

micelial |> 
  ggplot(aes(especie, tcm, fill = especie)) + 
  geom_boxplot() + 
  scale_fill_manual(values = viridis_pal(option = "viridis")(5), labels = expression(italic("F. asiaticum"), italic("F. austroamericanum"), italic("F. castaderiae"), italic("F. graminearum"), italic("F. meridionale"))) +
  labs (y = "Mycelium Growth Rate", x = " ", fill = "Species") +
    theme_classic()

ggsave("MGR.jpeg", dpi = 300, width = 9, height = 6)
```

```{r}
aov1 <- aov(tcm ~ especie, data = micelial)
summary(aov1)
```

```{r}
library(performance)
check_heteroscedasticity(aov1)
check_normality(aov1)
```

##Normality test

```{r}
hist(aov1$residuals)

qqnorm(aov1$residuals)
qqline(aov1$residuals)
```

```{r}
shapiro.test(aov1$residuals)
```

```{r}
library(DHARMa)
plot(simulateResiduals(aov1))
```

```{r}
insects <- as_tibble(InsectSprays) |> 
  select(spray, count)

insects |> 
  ggplot(aes(x = spray, y = count)) +
  geom_boxplot()
```

```{r}
aov2 <- aov(sqrt(count) ~ spray, data = insects)
summary(aov2)
```

```{r}
check_heteroscedasticity(aov2)
check_normality(aov2)
```

```{r}
library(emmeans)
aov2_means <- emmeans(aov2, ~ spray,
                      type = "response")
aov2_means

pwpm(aov2_means)
```

```{r}
library(multcomp)
library(multcompView)
cld(aov2_means)
```

```{r}
kruskal.test(count ~ spray, data = insects)
library(agricolae)
kruskal(insects$count, insects$spray,
        console = TRUE)
```

```{r}
glm1 <- glm(count ~ spray,
            data = insects,
            family = poisson(link = "identity"))
plot(simulateResiduals(glm1))
summary(glm1)
glm1_means <- emmeans(glm1, ~ spray)
cld(glm1_means)
```
